sudo: required

services:
  - docker

before_install:
  - docker build -t tokyor/rstudio .

## A few simple / crude tests
script:
  - docker run -d --name rstudio tokyor/rstudio
  - sleep 5 && docker ps | grep rstudio
  - docker rm -f $(docker ps -a -q)
